README.md
This fixes markdown parsing in Docusaurus.
=> Properly link schema file

.github/PULL_REQUEST_TEMPLATE.md
=> (IGNORE) Use sentence case in PR template

.github/workflows/ci.yml, .github/workflows/publish.yml, Cargo.lock, Cargo.toml, tests/integration.rs
=> Update to latest c2pa Rust SDK

Cargo.lock, src/main.rs
Display help if there are no arguments given on command line.
=> Display help if there are no arguments on the command line

README.md, src/config.rs
Fixing the environment variable name in README file
=> Fix an error in the README documentation

README.md
Updated README based on conversations with @crandmck
=> Remove Homebrew, Git installation methods, and add "update" wording

README.md
fixes errors in Readme related to --info
=> ((IGNORE) Update README description of --info flag

.github/workflows/ci.yml, .github/workflows/publish-and-release.yml
Adapted from https://github.com/adobe/xmp-toolkit-rs
* Build crate 3x/week and alert on error
* Include recommended fix for CodeCov flakiness
* Add notes about warnings in publish workflow
=> Build infrastructure improvements

Cargo.lock, Cargo.toml, README.md, src/fs_report.rs, src/info.rs
Updates to c2pa-rs version 0.17.0
=> update to cp2pa 0.17.0

Cargo.lock, Cargo.toml, README.md, schemas/ingredient.json, schemas/manifest-definition.json, src/main.rs, tests/fixtures/ingredient_test.json, tests/integration.rs
Adds support for many new formats
add ingredient_paths to support ingredients as files or JSON 
Updates to README and schema
Add simple ingredient report
injects c2patool claim_generator
=> (MINOR) New ingredient support and c2pa file formats

README.md
Change relative links to absolute per @dkozma
=> Change relative links to absolute to fix doc build

Cargo.lock, Cargo.toml, README.md, src/main.rs, tests/fixtures/ingredient_test.json, tests/integration.rs
Thumb and extension fixes
fix ingredient thumbnail loading
remove manifest preview feature
test for similar extensions
update c2pa-rs
Add svg support
=> Ingredient thumbnails, extension cleanup, toolkit update

Makefile
=> use compress-archive instead of tar

Cargo.lock, Cargo.toml
=> Updates to c2pa-rs 0.25.1

README.md, docs/manifest.md, docs/release-notes.md
Some minor doc cleanup.  This PR unblocks https://github.com/contentauth/opensource.contentauth.org/pull/77.
=> Fix issue with docusaurus styling and fix broken links

Cargo.lock, Cargo.toml, README.md
Updates to c2pa-rs 0.27.1
Adds mp3 support
Adds partial pdf support (read only)
=> C2pa Update, Add MP3 and some PDF

README.md, docs/manifest.md, docs/x_509.md
Docs only, paired with https://github.com/contentauth/opensource.contentauth.org/pull/76
All questions have been addressed and I have edited based on feedback from @gpeacock.  Ready for final review.
=> (IGNORE) Doc update for manifest docs

Cargo.lock, Cargo.toml
Will be used by the express / pdf team to test PDFs signed by express.
=> (MINOR) updates to c2pa-rs v0.28.2

.github/workflows/publish-and-release.yml
=> adds version to c2patool artifact names

docs/manifest.md
Closes https://github.com/contentauth/opensource.contentauth.org/issues/125
=> (IGNORE) Document how to specify an icon

Cargo.lock, Cargo.toml, README.md, deny.toml
Updates cargo packages and cargo.deny file.
Adds a readme update as well.
resolves PRs: 90, 100, 102, 109, & 165
=> Batch update for a list of simple merge PRs.

.github/workflows/ci.yml
=> only run tests/clippy if labeled

Cargo.lock, Cargo.toml, src/main.rs
Updated help strings around trust and signing
=> Pull latest c2pa-rs bug fixes into c2patool

CONTRIBUTING.md
Docs only: Update security guidance to link to SECURITY.md.
=> Update security guidance to link to SECURITY.md
