contentauth/c2patool

- .github/workflows/publish.yml
Removing `cargo install cargo-edit` from the publish workflow should save us about five minutes.
> (IGNORE) Remove cargo-edit from publish workflow

- .github/dependabot.yml
Fix copy/paste error in dependabot config when split out from c2pa-rs repo.
> (IGNORE) Fix dependabot config

- Cargo.lock
- Cargo.toml
- deny.toml
- src/main.rs
- src/signer.rs
Updates to c2pa-rs 0.11.0
The format of the ManifestReport has changed, The asset field is flattened into the manifest.
> Update to 0.11.0 c2pa-rs

- Cargo.lock
- Cargo.toml
- Makefile
- README.md
- src/info.rs
- src/main.rs
- src/manifest_config.rs
- tests/integration.rs
Adds a --info option to help with cloud manifests and determining embedded manifest size
Improves error reporting, more consistent
Updates c2pa sdk
> Add --info option 

- Cargo.lock
- Cargo.toml
- src/info.rs
- tests/integration.rs
Now fetches remote manifests for --info
better message when remote manifest fetch fails
> Fetch remote manifests for --info

- Cargo.lock
- README.md
- src/main.rs
- tests/integration.rs
Add --certs and --tree options
--certs extracts the certificate chain
--tree displays a graphic tree view of manifest store structure
(MINOR) added to catch changes from update to 0.17.0 c2pa-rs update.
> (MINOR) Add --certs and --tree options

- README.md
The README rendered on the doc site at https://opensource.contentauthenticity.org/docs/c2patool/ has a trivial formatting issue with an extra space on the line preceding a header defeating markdown parsing.  I hate to open a PR for such a trivial change, but it looks bad and makes the doc hard to peruse.
> Fix doc formatting 

- Cargo.lock
- Cargo.toml
- README.md
c2patool 0.5.4 introduced a 1.3 spec signature change that is not compatible with older sdks.
This version can validate the new signatures but does not write them
We want to avoid creating the new signatures until there are more clients that can read them.
> (MINOR) Update to c2pa-rs 0.24.0 - revert to previous signing model

- Makefile
- README.md
Switch from tar/compress to 7z for windows release
> Fix windows release

- CONTRIBUTING.md
- README.md
- docs/manifest.md
- docs/release-notes.md
- docs/x_509.md
This PR is paired with https://github.com/contentauth/opensource.contentauth.org/pull/77, which should be merged AFTER this one.
- Adds a new `docs` directory.
- Breaks up the README.md into 3 additional files in this directory that contain distinct content:
- `manifest.md` contains brief overview info on manifests and an example.  This will eventually be replaced with other content on the docs site per https://github.com/contentauth/opensource.contentauth.org/pull/76
- `x_509.md` contains the info on "creating and using an X.509 certificate".
- `release-notes.md` contains high-level release notes info.
To see how the docs will look when this PR is merged, see https://deploy-preview-77--cai-open-source.netlify.app/docs/c2patool/ which is the deploy preview for …
> (IGNORE) Split README into several files in new docs dir

- Cargo.lock
- Cargo.toml
(Fixes nightly build issues with openssl.)
> Upgrade to c2pa-rs 0.26.0

- README.md
Unfortunately, the relative link is broken when the doc is rendered on the doc site: https://opensource.contentauthenticity.org/docs/c2patool/#nightly-builds. 
Change to absolute URL fixes it.
Also added colon to UTC time, per [Adobe style guide](https://writing.adobe.com/58b352410/p/828b93-time).
> (IGNORE) Fix link to nightly build docs in README.md

- .github/workflows/ci.yml
- Makefile
- rustfmt.toml
- src/main.rs
- src/signer.rs
- tests/integration.rs
> (IGNORE) Apply same rustfmt configuration as c2pa-rs

- .github/workflows/publish-and-release.yml
Fixes asset name in publish action - should find correct c2patool asset, and upload with a versioned name.
> fixed c2patool asset name

- Cargo.lock
- Cargo.toml
- src/main.rs
Integrate with c2pa-rs 0.32.0, various test case fixes.
The sidecar option when used with remote was incorrectly embedding a manifest.
An error will now be displayed if you try to use -c or -m manifests without an output target.
At one point we supported a preview mode, but that is no longer supported. The error replaces empty output.
> Integrate with c2pa-rs 0.32.0, various test case fixes.

- .github/workflows/publish-and-release.yml
- Cargo.lock
- Cargo.toml
- README.md
Since users have had some issues installing from source due to building things like OpenSSL manually, this uses [cargo binstall](https://github.com/cargo-bins/cargo-binstall) to allow users to download and install c2patool more easily using prebuilt binaries.
The main advantage with starting with this over Homebrew is that this supports all platforms, where Homebrew only supports macOS.
**Note:** I haven't been able to really test this since its difficult without having the releases posted and the crates.io information up to date, but hopefully it works. We may need to post a follow-up release or commit to `main` if there are issues.
This resolves #176.
> Add better support for cargo-binstall

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/main.rs
`c2patool` isn't built as dependency to a Rust project, unlike `c2pa-rs`, so we can remove the toolchain version lock.
> Remove rust toolchain version lock

- Cargo.lock
- Cargo.toml
- src/main.rs
New commands to add and validate BMFF fragmented assets.  Support for globing to enables processing of complete DASH hierarchies.
> Initial fragment support

- README.md
This was missing from docs.  I reorganized the Usage section to include all the subcommands.
> Document fragment subcommand

- .github/workflows/ci.yml
(We don't have access to the CodeCov token, which means the upload will likely be rate-limited and fail.)
> chore: Skip CodeCov upload for non-member PRs

- README.md
Internal link in README was missing URL.
> doc: Fix broken link that was causing os site workflow to fail

- Cargo.lock
- Cargo.toml
This integrates c2pa-rs 0.37.0 with some fixes to the RegionOfInterest format as defined in the 2.1 spec.
> fix: Update c2pa-rs for RegionOfInterest support

- README.md
1. Describes the default behavior of the c2pa command line.
2. Describes the behavior when `trust` is in force and validation problems are found.
> enlarged description of c2pa command-line behavior

- .github/workflows/publish-and-release.yml
- Cargo.lock
- Cargo.toml
- deny.toml
* Uploads a **software bill of materials** for c2patool for each of our supported OSs during a release
* Adds `Instant` to our `deny.toml` ignore setting. This can be removed when https://github.com/contentauth/c2pa-rs/issues/663 is done and released.
> chore: uploads sbom as artifact
